sudo: required
services:
  - docker

before-install:
  - docker build -t lianglaw/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true lianglaw/frontend npm test -- --coverage

deploy:
  provider: elasticbeantalk
  region: 'us-east-2'
  app: 'react-docker'
  env: 'ReactDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-018178248469'
  bucket_path: 'react-docker'
  on:
    branch: 'master'
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
