sudo: required
services:
  - docker

before-install:
  - docker build -t lianglaw/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true lianglaw/frontend npm test -- --coverage
#purpose of CI -The test command will force Test to run in CI-mode
#                and tests will only run once instead of launching the watcher

docker:
  provider: elasticbeantalk
  region: 'us-east-2'
  app: 'react-docker'
  env: 'ReactDocker-env'
  bucket-name: 'elasticbeanstalk-us-east-2-018178248469'
  bucket-path: 'react-docker'
  on:
    branch: 'master'
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRETE_KEY'
